header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - "example/**"
    - "platform/server/shared/kitex_gen/**"
    - "platform/server/cmd/api/internal/biz/model/**"

  comment: on-failure