// Code generated by thriftgo (0.3.4). DO NOT EDIT.

package token

import (
	"context"
	"fmt"
	"github.com/cloudwego/cwgo/platform/server/shared/kitex_gen/model"
)

type AddTokenReq struct {
	RepositoryType   int32  `thrift:"repository_type,1" frugal:"1,default,i32" form:"repository_type,required" json:"repository_type,required"`
	RepositoryDomain string `thrift:"repository_domain,2" frugal:"2,default,string" form:"repository_domain,required" json:"repository_domain,required"`
	Token            string `thrift:"token,3" frugal:"3,default,string" form:"token,required" json:"token,required"`
}

func NewAddTokenReq() *AddTokenReq {
	return &AddTokenReq{}
}

func (p *AddTokenReq) InitDefault() {
	*p = AddTokenReq{}
}

func (p *AddTokenReq) GetRepositoryType() (v int32) {
	return p.RepositoryType
}

func (p *AddTokenReq) GetRepositoryDomain() (v string) {
	return p.RepositoryDomain
}

func (p *AddTokenReq) GetToken() (v string) {
	return p.Token
}
func (p *AddTokenReq) SetRepositoryType(val int32) {
	p.RepositoryType = val
}
func (p *AddTokenReq) SetRepositoryDomain(val string) {
	p.RepositoryDomain = val
}
func (p *AddTokenReq) SetToken(val string) {
	p.Token = val
}

func (p *AddTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddTokenReq(%+v)", *p)
}

type AddTokenResData struct {
	Owner          string `thrift:"owner,1" frugal:"1,default,string" form:"owner" json:"owner" query:"owner"`
	ExpirationTime string `thrift:"expiration_time,2" frugal:"2,default,string" form:"expiration_time" json:"expiration_time" query:"expiration_time"`
}

func NewAddTokenResData() *AddTokenResData {
	return &AddTokenResData{}
}

func (p *AddTokenResData) InitDefault() {
	*p = AddTokenResData{}
}

func (p *AddTokenResData) GetOwner() (v string) {
	return p.Owner
}

func (p *AddTokenResData) GetExpirationTime() (v string) {
	return p.ExpirationTime
}
func (p *AddTokenResData) SetOwner(val string) {
	p.Owner = val
}
func (p *AddTokenResData) SetExpirationTime(val string) {
	p.ExpirationTime = val
}

func (p *AddTokenResData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddTokenResData(%+v)", *p)
}

type AddTokenRes struct {
	Code int32            `thrift:"code,1" frugal:"1,default,i32" form:"code" json:"code" query:"code"`
	Msg  string           `thrift:"msg,2" frugal:"2,default,string" form:"msg" json:"msg" query:"msg"`
	Data *AddTokenResData `thrift:"data,3" frugal:"3,default,AddTokenResData" form:"data" json:"data" query:"data"`
}

func NewAddTokenRes() *AddTokenRes {
	return &AddTokenRes{}
}

func (p *AddTokenRes) InitDefault() {
	*p = AddTokenRes{}
}

func (p *AddTokenRes) GetCode() (v int32) {
	return p.Code
}

func (p *AddTokenRes) GetMsg() (v string) {
	return p.Msg
}

var AddTokenRes_Data_DEFAULT *AddTokenResData

func (p *AddTokenRes) GetData() (v *AddTokenResData) {
	if !p.IsSetData() {
		return AddTokenRes_Data_DEFAULT
	}
	return p.Data
}
func (p *AddTokenRes) SetCode(val int32) {
	p.Code = val
}
func (p *AddTokenRes) SetMsg(val string) {
	p.Msg = val
}
func (p *AddTokenRes) SetData(val *AddTokenResData) {
	p.Data = val
}

func (p *AddTokenRes) IsSetData() bool {
	return p.Data != nil
}

func (p *AddTokenRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddTokenRes(%+v)", *p)
}

type DeleteTokenReq struct {
	Ids []int64 `thrift:"ids,1" frugal:"1,default,list<i64>" form:"ids,required" json:"ids,required" vd:"len($)>0"`
}

func NewDeleteTokenReq() *DeleteTokenReq {
	return &DeleteTokenReq{}
}

func (p *DeleteTokenReq) InitDefault() {
	*p = DeleteTokenReq{}
}

func (p *DeleteTokenReq) GetIds() (v []int64) {
	return p.Ids
}
func (p *DeleteTokenReq) SetIds(val []int64) {
	p.Ids = val
}

func (p *DeleteTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteTokenReq(%+v)", *p)
}

type DeleteTokenRes struct {
	Code int32  `thrift:"code,1" frugal:"1,default,i32" form:"code" json:"code" query:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" form:"msg" json:"msg" query:"msg"`
}

func NewDeleteTokenRes() *DeleteTokenRes {
	return &DeleteTokenRes{}
}

func (p *DeleteTokenRes) InitDefault() {
	*p = DeleteTokenRes{}
}

func (p *DeleteTokenRes) GetCode() (v int32) {
	return p.Code
}

func (p *DeleteTokenRes) GetMsg() (v string) {
	return p.Msg
}
func (p *DeleteTokenRes) SetCode(val int32) {
	p.Code = val
}
func (p *DeleteTokenRes) SetMsg(val string) {
	p.Msg = val
}

func (p *DeleteTokenRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteTokenRes(%+v)", *p)
}

type GetTokenReq struct {
	Page             int32  `thrift:"page,1" frugal:"1,default,i32" json:"page" query:"page" vd:"$>=0"`
	Limit            int32  `thrift:"limit,2" frugal:"2,default,i32" json:"limit" query:"limit" vd:"$>=0"`
	Order            int32  `thrift:"order,3" frugal:"3,default,i32" json:"order" query:"order" vd:"$>=0"`
	OrderBy          string `thrift:"order_by,4" frugal:"4,default,string" json:"order_by" query:"order_by"`
	RepositoryType   int32  `thrift:"repository_type,5" frugal:"5,default,i32" json:"repository_type" query:"repository_type"`
	RepositoryDomain string `thrift:"repository_domain,6" frugal:"6,default,string" json:"repository_domain" query:"repository_domain"`
	Owner            string `thrift:"owner,7" frugal:"7,default,string" json:"owner" query:"owner"`
}

func NewGetTokenReq() *GetTokenReq {
	return &GetTokenReq{}
}

func (p *GetTokenReq) InitDefault() {
	*p = GetTokenReq{}
}

func (p *GetTokenReq) GetPage() (v int32) {
	return p.Page
}

func (p *GetTokenReq) GetLimit() (v int32) {
	return p.Limit
}

func (p *GetTokenReq) GetOrder() (v int32) {
	return p.Order
}

func (p *GetTokenReq) GetOrderBy() (v string) {
	return p.OrderBy
}

func (p *GetTokenReq) GetRepositoryType() (v int32) {
	return p.RepositoryType
}

func (p *GetTokenReq) GetRepositoryDomain() (v string) {
	return p.RepositoryDomain
}

func (p *GetTokenReq) GetOwner() (v string) {
	return p.Owner
}
func (p *GetTokenReq) SetPage(val int32) {
	p.Page = val
}
func (p *GetTokenReq) SetLimit(val int32) {
	p.Limit = val
}
func (p *GetTokenReq) SetOrder(val int32) {
	p.Order = val
}
func (p *GetTokenReq) SetOrderBy(val string) {
	p.OrderBy = val
}
func (p *GetTokenReq) SetRepositoryType(val int32) {
	p.RepositoryType = val
}
func (p *GetTokenReq) SetRepositoryDomain(val string) {
	p.RepositoryDomain = val
}
func (p *GetTokenReq) SetOwner(val string) {
	p.Owner = val
}

func (p *GetTokenReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTokenReq(%+v)", *p)
}

type GetTokenResData struct {
	Tokens []*model.Token `thrift:"tokens,1" frugal:"1,default,list<model.Token>" form:"tokens" json:"tokens" query:"tokens"`
	Total  int32          `thrift:"total,2" frugal:"2,default,i32" form:"total" json:"total" query:"total"`
}

func NewGetTokenResData() *GetTokenResData {
	return &GetTokenResData{}
}

func (p *GetTokenResData) InitDefault() {
	*p = GetTokenResData{}
}

func (p *GetTokenResData) GetTokens() (v []*model.Token) {
	return p.Tokens
}

func (p *GetTokenResData) GetTotal() (v int32) {
	return p.Total
}
func (p *GetTokenResData) SetTokens(val []*model.Token) {
	p.Tokens = val
}
func (p *GetTokenResData) SetTotal(val int32) {
	p.Total = val
}

func (p *GetTokenResData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTokenResData(%+v)", *p)
}

type GetTokenRes struct {
	Code int32            `thrift:"code,1" frugal:"1,default,i32" form:"code" json:"code" query:"code"`
	Msg  string           `thrift:"msg,2" frugal:"2,default,string" form:"msg" json:"msg" query:"msg"`
	Data *GetTokenResData `thrift:"data,3" frugal:"3,default,GetTokenResData" form:"data" json:"data" query:"data"`
}

func NewGetTokenRes() *GetTokenRes {
	return &GetTokenRes{}
}

func (p *GetTokenRes) InitDefault() {
	*p = GetTokenRes{}
}

func (p *GetTokenRes) GetCode() (v int32) {
	return p.Code
}

func (p *GetTokenRes) GetMsg() (v string) {
	return p.Msg
}

var GetTokenRes_Data_DEFAULT *GetTokenResData

func (p *GetTokenRes) GetData() (v *GetTokenResData) {
	if !p.IsSetData() {
		return GetTokenRes_Data_DEFAULT
	}
	return p.Data
}
func (p *GetTokenRes) SetCode(val int32) {
	p.Code = val
}
func (p *GetTokenRes) SetMsg(val string) {
	p.Msg = val
}
func (p *GetTokenRes) SetData(val *GetTokenResData) {
	p.Data = val
}

func (p *GetTokenRes) IsSetData() bool {
	return p.Data != nil
}

func (p *GetTokenRes) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTokenRes(%+v)", *p)
}

type TokenService interface {
	AddToken(ctx context.Context, req *AddTokenReq) (r *AddTokenRes, err error)

	DeleteToken(ctx context.Context, req *DeleteTokenReq) (r *DeleteTokenRes, err error)

	GetToken(ctx context.Context, req *GetTokenReq) (r *GetTokenRes, err error)
}
