/*
 *
 * Copyright 2023 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package router

import (
	"github.com/cloudwego/cwgo/platform/server/cmd/api/internal/biz/router/base"
	"github.com/cloudwego/cwgo/platform/server/cmd/api/internal/biz/router/idl"
	registry "github.com/cloudwego/cwgo/platform/server/cmd/api/internal/biz/router/registry"
	"github.com/cloudwego/cwgo/platform/server/cmd/api/internal/biz/router/repository"
	"github.com/cloudwego/cwgo/platform/server/cmd/api/internal/biz/router/template"
	token "github.com/cloudwego/cwgo/platform/server/cmd/api/internal/biz/router/token"
	"github.com/cloudwego/cwgo/platform/server/shared/config"
	"github.com/cloudwego/cwgo/platform/server/shared/consts"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	// INSERT_POINT: DO NOT DELETE THIS LINE!
	token.Register(r)

	if config.GetManager().ApiConfigManager.RegistryConfigManager.GetRegistryType() == consts.RegistryTypeNumBuiltin {
		registry.Register(r)
	}

	template.Register(r)

	repository.Register(r)

	idl.Register(r)

	base.Register(r)
}
