// Code generated by Kitex v0.6.1. DO NOT EDIT.

package agentservice

import (
	"context"
	agent "github.com/cloudwego/cwgo/platform/server/shared/kitex_gen/agent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return agentServiceServiceInfo
}

var agentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "AgentService"
	handlerType := (*agent.AgentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"AddRepository":          kitex.NewMethodInfo(addRepositoryHandler, newAgentServiceAddRepositoryArgs, newAgentServiceAddRepositoryResult, false),
		"UpdateRepositoryStatus": kitex.NewMethodInfo(updateRepositoryStatusHandler, newAgentServiceUpdateRepositoryStatusArgs, newAgentServiceUpdateRepositoryStatusResult, false),
		"SyncRepositoryById":     kitex.NewMethodInfo(syncRepositoryByIdHandler, newAgentServiceSyncRepositoryByIdArgs, newAgentServiceSyncRepositoryByIdResult, false),
		"AddIDL":                 kitex.NewMethodInfo(addIDLHandler, newAgentServiceAddIDLArgs, newAgentServiceAddIDLResult, false),
		"SyncIDLsById":           kitex.NewMethodInfo(syncIDLsByIdHandler, newAgentServiceSyncIDLsByIdArgs, newAgentServiceSyncIDLsByIdResult, false),
		"UpdateTasks":            kitex.NewMethodInfo(updateTasksHandler, newAgentServiceUpdateTasksArgs, newAgentServiceUpdateTasksResult, false),
		"GenerateCode":           kitex.NewMethodInfo(generateCodeHandler, newAgentServiceGenerateCodeArgs, newAgentServiceGenerateCodeResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "agent",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func addRepositoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceAddRepositoryArgs)
	realResult := result.(*agent.AgentServiceAddRepositoryResult)
	success, err := handler.(agent.AgentService).AddRepository(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceAddRepositoryArgs() interface{} {
	return agent.NewAgentServiceAddRepositoryArgs()
}

func newAgentServiceAddRepositoryResult() interface{} {
	return agent.NewAgentServiceAddRepositoryResult()
}

func updateRepositoryStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceUpdateRepositoryStatusArgs)
	realResult := result.(*agent.AgentServiceUpdateRepositoryStatusResult)
	success, err := handler.(agent.AgentService).UpdateRepositoryStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceUpdateRepositoryStatusArgs() interface{} {
	return agent.NewAgentServiceUpdateRepositoryStatusArgs()
}

func newAgentServiceUpdateRepositoryStatusResult() interface{} {
	return agent.NewAgentServiceUpdateRepositoryStatusResult()
}

func syncRepositoryByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceSyncRepositoryByIdArgs)
	realResult := result.(*agent.AgentServiceSyncRepositoryByIdResult)
	success, err := handler.(agent.AgentService).SyncRepositoryById(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceSyncRepositoryByIdArgs() interface{} {
	return agent.NewAgentServiceSyncRepositoryByIdArgs()
}

func newAgentServiceSyncRepositoryByIdResult() interface{} {
	return agent.NewAgentServiceSyncRepositoryByIdResult()
}

func addIDLHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceAddIDLArgs)
	realResult := result.(*agent.AgentServiceAddIDLResult)
	success, err := handler.(agent.AgentService).AddIDL(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceAddIDLArgs() interface{} {
	return agent.NewAgentServiceAddIDLArgs()
}

func newAgentServiceAddIDLResult() interface{} {
	return agent.NewAgentServiceAddIDLResult()
}

func syncIDLsByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceSyncIDLsByIdArgs)
	realResult := result.(*agent.AgentServiceSyncIDLsByIdResult)
	success, err := handler.(agent.AgentService).SyncIDLsById(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceSyncIDLsByIdArgs() interface{} {
	return agent.NewAgentServiceSyncIDLsByIdArgs()
}

func newAgentServiceSyncIDLsByIdResult() interface{} {
	return agent.NewAgentServiceSyncIDLsByIdResult()
}

func updateTasksHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceUpdateTasksArgs)
	realResult := result.(*agent.AgentServiceUpdateTasksResult)
	success, err := handler.(agent.AgentService).UpdateTasks(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceUpdateTasksArgs() interface{} {
	return agent.NewAgentServiceUpdateTasksArgs()
}

func newAgentServiceUpdateTasksResult() interface{} {
	return agent.NewAgentServiceUpdateTasksResult()
}

func generateCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceGenerateCodeArgs)
	realResult := result.(*agent.AgentServiceGenerateCodeResult)
	success, err := handler.(agent.AgentService).GenerateCode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceGenerateCodeArgs() interface{} {
	return agent.NewAgentServiceGenerateCodeArgs()
}

func newAgentServiceGenerateCodeResult() interface{} {
	return agent.NewAgentServiceGenerateCodeResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddRepository(ctx context.Context, req *agent.AddRepositoryReq) (r *agent.AddRepositoryRes, err error) {
	var _args agent.AgentServiceAddRepositoryArgs
	_args.Req = req
	var _result agent.AgentServiceAddRepositoryResult
	if err = p.c.Call(ctx, "AddRepository", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateRepositoryStatus(ctx context.Context, req *agent.UpdateRepositoryStatusReq) (r *agent.UpdateRepositoryStatusRes, err error) {
	var _args agent.AgentServiceUpdateRepositoryStatusArgs
	_args.Req = req
	var _result agent.AgentServiceUpdateRepositoryStatusResult
	if err = p.c.Call(ctx, "UpdateRepositoryStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SyncRepositoryById(ctx context.Context, req *agent.SyncRepositoryByIdReq) (r *agent.SyncRepositoryByIdRes, err error) {
	var _args agent.AgentServiceSyncRepositoryByIdArgs
	_args.Req = req
	var _result agent.AgentServiceSyncRepositoryByIdResult
	if err = p.c.Call(ctx, "SyncRepositoryById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddIDL(ctx context.Context, req *agent.AddIDLReq) (r *agent.AddIDLRes, err error) {
	var _args agent.AgentServiceAddIDLArgs
	_args.Req = req
	var _result agent.AgentServiceAddIDLResult
	if err = p.c.Call(ctx, "AddIDL", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SyncIDLsById(ctx context.Context, req *agent.SyncIDLsByIdReq) (r *agent.SyncIDLsByIdRes, err error) {
	var _args agent.AgentServiceSyncIDLsByIdArgs
	_args.Req = req
	var _result agent.AgentServiceSyncIDLsByIdResult
	if err = p.c.Call(ctx, "SyncIDLsById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateTasks(ctx context.Context, req *agent.UpdateTasksReq) (r *agent.UpdateTasksRes, err error) {
	var _args agent.AgentServiceUpdateTasksArgs
	_args.Req = req
	var _result agent.AgentServiceUpdateTasksResult
	if err = p.c.Call(ctx, "UpdateTasks", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GenerateCode(ctx context.Context, req *agent.GenerateCodeReq) (r *agent.GenerateCodeRes, err error) {
	var _args agent.AgentServiceGenerateCodeArgs
	_args.Req = req
	var _result agent.AgentServiceGenerateCodeResult
	if err = p.c.Call(ctx, "GenerateCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
